# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-31 16:48
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssertionReasonA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstno', models.CharField(default=None, max_length=10)),
                ('secondno', models.CharField(default=None, max_length=10)),
                ('score', models.IntegerField(default=0)),
                ('explanation', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='AssertionReasonQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opno', models.CharField(default=None, max_length=10)),
                ('opcontent', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Finished_Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FreeTextA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=2000)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FreeTextQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='LinkedA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opno', models.CharField(default=None, max_length=10)),
                ('linkno', models.CharField(default=None, max_length=10)),
                ('score', models.IntegerField(default=0)),
                ('explanation', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='LinkedQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MultipleChoiceA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opno', models.CharField(default=None, max_length=10)),
                ('opscore', models.IntegerField(default=0)),
                ('explanation', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='MultipleChoiceQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opno', models.CharField(default=None, max_length=10)),
                ('opcontent', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionid', models.IntegerField(default=0, unique=True)),
                ('description', models.CharField(max_length=2000)),
                ('type', models.CharField(choices=[('default', 'Please select:'), ('Free Text', 'Free Text'), ('Multiple Choice', 'Multiple Choice'), ('Linked', 'Linked'), ('Assertion Reason', 'Assertion Reason')], default='default', max_length=30)),
                ('video', models.FileField(blank=True, upload_to='questions', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'ogg'])], verbose_name='Video Upload')),
                ('image', models.FileField(blank=True, upload_to='questions', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg', 'jpg'])], verbose_name='Thumbnail Upload')),
                ('explanation', models.CharField(blank=True, max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(choices=[('default', 'Please select:'), ('Social Engineering', 'Social Engineering'), ('Password Design', 'Password Design'), ('Side-channel Attack', 'Side-channel Attack'), ('Malwares', 'Malwares')], default='default', max_length=30)),
                ('description', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, upload_to='profile_images')),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('score', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hcseduapp.Topic'),
        ),
        migrations.AddField(
            model_name='multiplechoiceq',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hcseduapp.Question'),
        ),
        migrations.AddField(
            model_name='multiplechoicea',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hcseduapp.Question'),
        ),
        migrations.AddField(
            model_name='linkedq',
            name='linkedid',
            field=models.ForeignKey(db_column='questionid', on_delete=django.db.models.deletion.CASCADE, related_name='linked_question_id', to='hcseduapp.Question', to_field='questionid'),
        ),
        migrations.AddField(
            model_name='linkedq',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_id', to='hcseduapp.Question'),
        ),
        migrations.AddField(
            model_name='linkeda',
            name='linkedid',
            field=models.ForeignKey(db_column='questionid', on_delete=django.db.models.deletion.CASCADE, related_name='linked_question_answer_id', to='hcseduapp.Question', to_field='questionid'),
        ),
        migrations.AddField(
            model_name='linkeda',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_answer_id', to='hcseduapp.Question'),
        ),
        migrations.AddField(
            model_name='freetextq',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hcseduapp.Question'),
        ),
        migrations.AddField(
            model_name='freetexta',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hcseduapp.Question'),
        ),
        migrations.AddField(
            model_name='finished_questions',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hcseduapp.Question'),
        ),
        migrations.AddField(
            model_name='finished_questions',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assertionreasonq',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hcseduapp.Question'),
        ),
        migrations.AddField(
            model_name='assertionreasona',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hcseduapp.Question'),
        ),
        migrations.AlterUniqueTogether(
            name='multiplechoicea',
            unique_together=set([('question', 'opno')]),
        ),
        migrations.AlterUniqueTogether(
            name='linkedq',
            unique_together=set([('question', 'linkedid')]),
        ),
        migrations.AlterUniqueTogether(
            name='linkeda',
            unique_together=set([('question', 'opno', 'linkedid', 'linkno')]),
        ),
        migrations.AlterUniqueTogether(
            name='assertionreasona',
            unique_together=set([('question', 'firstno', 'secondno')]),
        ),
    ]
