# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-31 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcseduapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=models.CharField(blank=True, default='null', max_length=2000),
        ),
    ]
