# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-01 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcseduapp', '0002_auto_20190731_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='linkedstatus',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('default', 'Please select:'), ('Free Text', 'Free Text'), ('Multiple Choice', 'Multiple Choice'), ('Assertion Reason', 'Assertion Reason')], default='default', max_length=30),
        ),
    ]
