# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-05 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcseduapp', '0003_auto_20190801_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='finished_questions',
            name='answer',
            field=models.CharField(default=None, max_length=2000),
        ),
    ]
