# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-07 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcseduapp', '0004_finished_questions_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.CharField(choices=[('default', 'Please select:'), ('Free Text', 'Free Text'), ('Multiple Choice', 'Multiple Choice'), ('Assertion Reason', 'Assertion Reason')], default='default', max_length=30),
        ),
        migrations.AlterField(
            model_name='question',
            name='video',
            field=models.CharField(choices=[('default', 'Please select:'), ('Free Text', 'Free Text'), ('Multiple Choice', 'Multiple Choice'), ('Assertion Reason', 'Assertion Reason')], default='default', max_length=30),
        ),
    ]
