# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-07 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcseduapp', '0005_auto_20190807_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='video',
            field=models.CharField(max_length=50),
        ),
    ]
