# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-12 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcseduapp', '0009_auto_20190812_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedq',
            name='opno',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
