# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-16 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcseduapp', '0010_linkedq_opno'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiplechoicea',
            name='video',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
