# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-27 15:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hcseduapp', '0013_singleoption_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freetextq',
            name='question',
        ),
        migrations.AlterUniqueTogether(
            name='linkeda',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='linkeda',
            name='linkedid',
        ),
        migrations.RemoveField(
            model_name='linkeda',
            name='question',
        ),
        migrations.DeleteModel(
            name='FreeTextQ',
        ),
        migrations.DeleteModel(
            name='LinkedA',
        ),
    ]
